language: node_js
node_js: stable
sudo: required
dist: trusty
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run polymer test
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
